apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: studentapi
  name: studentapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentapi
  template:
    metadata:
      labels:
        app: studentapi
    spec:
      containers:
      - image: sebaspp/studentapi:{{.Values.env.APP_VERSION }}
        name: studentapi
        ports:
        - containerPort: 8080
        env: 
        - name: DB_HOST
          value: mysql
        - name: DB_NAME
          value: student
        - name: DB_PASSWORD
          value: root
        - name: DB_USERNAME
          value: root
        startupProbe:
          httpGet:
            path: /student/health
            port: 8080
          failureThreshold: 30
          periodSeconds: 50
        livenessProbe:
          httpGet:
            path: /student/health
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 3
          periodSeconds: 50
          successThreshold: 1
          failureThreshold: 5
        resources: 
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"