apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: studentapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: studentapi
  minReplicas: {{.Values.autoscalingmin}}
  maxReplicas: {{.Values.autoscalingmax}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60