name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Helm Install
        run: |
          helm install aplication ./helmapi --values ./helmapi/values.yaml
          helm install aplication ./helmbd --values ./helmbd/values.yaml
